###Name:Dibyanshu Ratna Bajracharya

###Class:L5CG2

### Student Id: 2408571

#4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
**Problem - 1: Array Creation:**
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# Q1.
q1 = np.empty((2, 2))
print("Empty Array:\n",q1,"\n")

#Q2
q2 = np.ones((4,2))
print("Ones Arryay:\n",q2,"\n")

#Q3
fill_value = 7
q3 = np.full((3, 3), fill_value)
print("Fill Value Array:\n",q3,"\n")

#Q4
given_array_zero = np.array([[1,2,3],[4,5,6]])
q4 = np.zeros_like(given_array_zero)
print("Shaped Zero Array:\n",q4,"\n")

#Q5
given_array_one = np.array([[4,5],[5,7]])
q5 = np.ones_like(given_array_one)
print("Shaped Ones Array",q5,"\n")

#Q6
new_list = [1,2,3,4]
q6 = np.array(new_list)
print("List to Array:\n",q6)

Empty Array:
 [[1.78e-322 2.17e-322]
 [6.42e-323 7.91e-323]] 

Ones Arryay:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

Fill Value Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

Shaped Zero Array:
 [[0 0 0]
 [0 0 0]] 

Shaped Ones Array [[1 1]
 [1 1]] 

List to Array:
 [1 2 3 4]


#4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
**Complete the following tasks:**
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

#Q1
q1 = np.arange(10,50)
print("Ranging Matrix:\n",q1,"\n")

#Q2
given_array = np.arange(0,9)
q2 = np.reshape(given_array,(3,3))
print("Reshape matrix:\n",q2,"\n")

#Q3
q3 = np.eye(3)
print("Identity matrix:\n",q3,"\n")

#Q4
random_array = np.random.random(30)
print("Mean:",random_array.mean(),"\n")

#Q5
array_random = np.random.random((10, 10))
min_value = np.min(array_random)
max_value = np.max(array_random)
print("Maximum Value:",max_value)
print("Minimum Value:",min_value)
print("\n")

#Q6
zero_array = np.zeros(10)
zero_array[5] = 1
print("Replace Array:\n",zero_array)
print("\n")

#Q7
arr = np.array([1,2,0,0,4,0])
print("Reverse Array:\n",arr[::-1])
print("\n")

#Q8
one_border = np.ones((3,3))
one_border[1:-1,1:-1] = 0
print("2D Array\n",one_border,"\n")

#Q9
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("CheckBox:\n",checker)

Ranging Matrix:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

Reshape matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Mean: 0.5094284346116876 

Maximum Value: 0.9925440555548576
Minimum Value: 0.009112533285448476


Replace Array:
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Reverse Array:
 [0 4 0 0 2 1]


2D Array
 [[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]] 

CheckBox:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#Q1
print("Sum:")
print(x+y,",")
print(v+w)
print("\n")

#Q2
print("Difference:")
print(x-y,",")
print(v-w)
print("\n")

#Q3
print("Multiplication:")
print(2*x,",")
print(5*y,",")
print(3*v,",")
print(9*w)
print("\n")

#Q4
print("Square:")
print(np.square(x),",")
print(np.square(y),",")
print(np.square(v),",")
print(np.square(w))
print("\n")

#Q5
print("Dot Product:")
print(np.dot(v,w),",")
print(np.dot(x,v),",")
print(np.dot(x,y))
print("\n")

#Q6
print("Concatenate:")
print(np.concatenate((x,y),axis=0),",")
print(np.vstack((v, w)))

#Q7
# print(np.concatenate((x,v),axis=1))
# The error occurs because x is a 2D array, and v is a 1D array, so their shapes are incompatible for concatenation along the specified axis.

Sum:
[[ 6  8]
 [10 13]] ,
[20 22]


Difference:
[[-4 -4]
 [-4 -3]] ,
[-2 -2]


Multiplication:
[[ 2  4]
 [ 6 10]] ,
[[25 30]
 [35 40]] ,
[27 30] ,
[ 99 108]


Square:
[[ 1  4]
 [ 9 25]] ,
[[25 36]
 [49 64]] ,
[ 81 100] ,
[121 144]


Dot Product:
219 ,
[29 77] ,
[[19 22]
 [50 58]]


Concatenate:
[[1 2]
 [3 5]
 [5 6]
 [7 8]] ,
[[ 9 10]
 [11 12]]


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A^−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)^T = B^TA^T
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#Q1
AIn = np.linalg.inv(A)
print("A.A^-1:",np.dot(A,AIn),"\n")

#Q2
A_B = np.dot(A,B)
B_A = np.dot(B,A)
print("AB:",A_B)
print(" ̸= ")
print("BA:",B_A,"\n")

#Q3
A_BT = A_B.T
AT = A.T
BT = B.T
BT_AT = np.dot(BT,AT)
print("(AB)^T:",A_BT)
print("=")
print("B^TA^T:",BT_AT,"\n")

#Q4
x = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
y = np.array([-1, -3, 9])

x_inv = np.linalg.inv(x)

z = np.dot(x_inv,y)
print("Solution using the Inverse Method:")
print(z)

A.A^-1: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]] 

AB: [[23 13]
 [51 29]]
 ̸= 
BA: [[36 44]
 [13 16]] 

(AB)^T: [[23 51]
 [13 29]]
=
B^TA^T: [[23 51]
 [13 29]] 

Solution using the Inverse Method:
[ 2.  1. -2.]


# 4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size
size = 1000000

# Create two lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]

# Python Lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken for Python Lists: {end_time - start_time:.5f} sec")

# Create two arrays
array1 = np.arange(size)
array2 = np.arange(size, 2*size)

# NumPy Arrays
start_time = time.time()
result_array = array1 + array2
end_time = time.time()
print(f"Time taken for NumPy Arrays: {end_time - start_time:.5f} sec")


Time taken for Python Lists: 0.17163 sec
Time taken for NumPy Arrays: 0.00400 sec


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size
size = 1000000

# Create two lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]

# Python Lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print(f"Time taken for Python Lists: {end_time - start_time:.5f} sec")

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size, 2*size)

# NumPy Arrays
start_time = time.time()
result_array = array1 * array2
end_time = time.time()
print(f"Time taken for NumPy Arrays: {end_time - start_time:.5f} sec")


Time taken for Python Lists: 0.15566 sec
Time taken for NumPy Arrays: 0.00426 sec


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import time
import numpy as np

# Define the size of the lists
size = 1000000

# Create two lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size, 2*size)]

# Python Lists
start_time = time.time()
result_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print(f"Time taken Python Lists: {end_time - start_time:.5f} sec")

# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size, 2*size)

# NumPy Arrays
start_time = time.time()
result_array = np.dot(array1, array2)
end_time = time.time()
print(f"Time taken for NumPy Arrays: {end_time - start_time:.5f} sec")


Time taken Python Lists: 1.11623 sec
Time taken for NumPy Arrays: 0.01028 sec


**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import time
import numpy as np

# Define the size
size = 100

# Create two 1000x1000 matrices
matrix1 = [[i + j for i in range(size)] for j in range(size)]
matrix2 = [[i + j for i in range(size)] for j in range(size)]

# Python Lists
start_time = time.time()
result_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(size)) for j in range(size)] for i in range(size)]
end_time = time.time()
print(f"Time taken Python Lists: {end_time - start_time:.5f} sec")

# Create two 1000x1000 matrices
matrix1_np = np.random.randint(0, 10, size=(size, size))
matrix2_np = np.random.randint(0, 10, size=(size, size))

# NumPy Arrays
start_time = time.time()
result_array = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print(f"Time taken for NumPy Arrays: {end_time - start_time:.5f} sec")


Time taken Python Lists: 0.16450 sec
Time taken for NumPy Arrays: 0.00106 sec
